%YAML 1.2
---
gpu: 0

dataset:
  input_train: '/home/gridsan/pnegi/maia-chess/sampledata/training/*/*' # This uses glob so training/*/* is probably the end
  input_test: '/home/gridsan/pnegi/maia-chess/sampledata/validation/*/*' # This uses glob so validate/*/* is probably the end

training:
    precision: 'half'
    batch_size: 4096
    num_batch_splits: 4
    test_steps: 50
    train_avg_report_steps: 50
    total_steps: 400000
    checkpoint_steps: 10000
    shuffle_size: 250000
    lr_values:
        - 0.01
        - 0.001
        - 0.0001
    lr_boundaries:
        - 80000
        - 200000
        - 360000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
...
